from docx import Document
from docx.shared import Inches

doc = Document()

doc.add_heading('Explicacion de las Visualizaciones - Codigo Fuente', 0)
doc.add_paragraph('Documento que detalla como se genera cada grafica del proyecto y que parte del codigo se encarga de ello.')
doc.add_paragraph()

# ===== GLOBAL =====
doc.add_heading('Funcion encargada de las graficas', 1)
doc.add_paragraph('Todas las graficas se generan dentro de la funcion generar_visualizaciones(resultados, df), definida en la linea 147 del archivo analisis_supermercado.py. Esta funcion recibe dos parametros:')
doc.add_paragraph('resultados: diccionario con los datos procesados provenientes de la funcion ejecutar_analisis()')
doc.add_paragraph('df: el DataFrame original con los datos limpios')
doc.add_paragraph('La funcion retorna una lista (archivos_plot) con los nombres de los 5 archivos PNG generados.')
doc.add_paragraph()

# ===== 1 =====
doc.add_heading('1. promedio_ventas_categoria.png', 2)
doc.add_paragraph('Tipo: Grafica de barras verticales')
doc.add_paragraph('Que muestra: El promedio de ventas (Sales) para cada categoria de producto (Product Category).')
doc.add_paragraph()
doc.add_heading('Preparacion de los datos (ejecutar_analisis, lineas 77-78)', 3)
doc.add_paragraph('promedio_ventas_cat = df.groupby("Product Category")["Sales"].mean().reset_index()')
doc.add_paragraph('promedio_ventas_cat = promedio_ventas_cat.sort_values(by="Sales", ascending=False)')
doc.add_paragraph('Se agrupan todos los registros por la columna Product Category, se calcula el promedio de Sales dentro de cada grupo, se ordena de mayor a menor y se guarda en resultados["promedio_ventas_cat"].')
doc.add_paragraph()
doc.add_heading('Generacion de la grafica (lineas 153-164)', 3)
doc.add_paragraph('plt.figure() - Crea una nueva figura en blanco.')
doc.add_paragraph('sns.barplot(x="Product Category", y="Sales", data=resultados["promedio_ventas_cat"], hue="Product Category", palette="viridis", legend=False) - Dibuja las barras tomando Product Category en el eje X y Sales en el eje Y. La paleta de colores viridis asigna un color distinto a cada categoria. El parametro hue evita advertencias de seaborn 0.14+ y legend=False suprime la leyenda porque las etiquetas ya estan en el eje X.')
doc.add_paragraph('plt.title() / plt.xlabel() / plt.ylabel() - Agregan titulo y etiquetas a los ejes.')
doc.add_paragraph('plt.xticks(rotation=45) - Rota 45 grados las etiquetas del eje X para que no se superpongan.')
doc.add_paragraph('plt.tight_layout() - Ajusta automaticamente los margenes.')
doc.add_paragraph('plt.savefig("promedio_ventas_categoria.png") - Guarda la figura como archivo PNG.')
doc.add_paragraph('plt.close() - Cierra la figura para liberar memoria.')
doc.add_paragraph()

# ===== 2 =====
doc.add_heading('2. top_ciudades.png', 2)
doc.add_paragraph('Tipo: Grafica de barras horizontales')
doc.add_paragraph('Que muestra: Las 5 ciudades con mayor ganancia total (Profit), ordenadas de mayor a menor.')
doc.add_paragraph()
doc.add_heading('Preparacion de los datos (ejecutar_analisis, lineas 87-88)', 3)
doc.add_paragraph('top_ciudades = df.groupby("City")["Profit"].sum().reset_index()')
doc.add_paragraph('top_ciudades = top_ciudades.sort_values(by="Profit", ascending=False).head(5)')
doc.add_paragraph('Se agrupa por ciudad, se suma Profit en cada una, se ordena descendente y se toman solo las primeras 5 filas. Se guarda en resultados["top_ciudades"].')
doc.add_paragraph()
doc.add_heading('Generacion de la grafica (lineas 167-177)', 3)
doc.add_paragraph('plt.figure() - Nueva figura.')
doc.add_paragraph('sns.barplot(x="Profit", y="City", ...) - En este caso Profit va en el eje X y City en el eje Y, lo que genera barras horizontales. Se usa palette="magma" para colores y hue="City" con legend=False como en la grafica anterior.')
doc.add_paragraph('El titulo es "Top 5 Ciudades con Mayor Ganancia". No se rota el eje porque las etiquetas de Ciudad son cortas. Se guarda como top_ciudades.png.')
doc.add_paragraph()

# ===== 3 =====
doc.add_heading('3. ventas_por_mes.png', 2)
doc.add_paragraph('Tipo: Grafica de lineas con marcadores')
doc.add_paragraph('Que muestra: La suma total de ventas (Sales) para cada mes del ano 2015.')
doc.add_paragraph()
doc.add_heading('Preparacion de los datos (ejecutar_analisis, lineas 122-125)', 3)
doc.add_paragraph('df["Month"] = df["Order Date"].dt.month - Extrae el numero del mes (1-12) de la columna Order Date.')
doc.add_paragraph('df["Month_Name"] = df["Order Date"].dt.strftime("%B") - Extrae el nombre del mes en ingles (January, February, etc.).')
doc.add_paragraph('ventas_por_mes = df.groupby(["Month", "Month_Name"])["Sales"].sum().reset_index() - Agrupa por mes y suma ventas.')
doc.add_paragraph('ventas_por_mes = ventas_por_mes.sort_values(by="Month") - Ordena cronologicamente por numero de mes.')
doc.add_paragraph()
doc.add_heading('Generacion de la grafica (lineas 180-192)', 3)
doc.add_paragraph('plt.plot() - Funcion de matplotlib para graficas de linea. Recibe Month en el eje X, Sales en el eje Y. marker="o" agrega circulos en cada punto de datos. color="b" establece el color azul.')
doc.add_paragraph('plt.xticks(... rotation=45) - Reemplaza los numeros de mes (1,2,3...) por los nombres (January, February...) y los rota 45 grados.')
doc.add_paragraph('plt.grid(True) - Activa la cuadricula para facilitar la lectura.')
doc.add_paragraph('Nota: A diferencia de las barras que usan seaborn, esta grafica usa matplotlib puro (plt.plot).')
doc.add_paragraph()

# ===== 4 =====
doc.add_heading('4. descuento_vs_ganancia.png', 2)
doc.add_paragraph('Tipo: Grafica de dispersion (scatter plot)')
doc.add_paragraph('Que muestra: La relacion entre el descuento aplicado (Discount) y la ganancia obtenida (Profit) en cada pedido. Cada punto es un pedido individual.')
doc.add_paragraph()
doc.add_heading('Preparacion de los datos (ninguna adicional)', 3)
doc.add_paragraph('Esta grafica utiliza directamente el DataFrame df original, sin agrupacion previa. Toma las columnas Discount y Profit de cada una de las 1952 filas.')
doc.add_paragraph()
doc.add_heading('Generacion de la grafica (lineas 195-205)', 3)
doc.add_paragraph('sns.scatterplot(x="Discount", y="Profit", data=df, alpha=0.6, color="g") - Dibuja un punto por cada fila del DataFrame. alpha=0.6 da transparencia a los puntos para evitar solapamiento visual. color="g" establece color verde.')
doc.add_paragraph('No se usa palette porque no hay variable categorica. Es una relacion directa entre dos variables numericas.')
doc.add_paragraph('Se guarda como descuento_vs_ganancia.png.')
doc.add_paragraph()

# ===== 5 =====
doc.add_heading('5. productos_perdida.png', 2)
doc.add_paragraph('Tipo: Grafica de barras horizontales')
doc.add_paragraph('Que muestra: El top 10 de productos con mayores perdidas (Profit negativo mas bajo).')
doc.add_paragraph()
doc.add_heading('Preparacion de los datos (ejecutar_analisis, lineas 135-136)', 3)
doc.add_paragraph('productos_perdida = df[df["Profit"] < 0].groupby("Product Name")["Profit"].sum().reset_index() - Primero se filtran solo los registros con Profit negativo, luego se agrupa por producto y se suman las perdidas.')
doc.add_paragraph('productos_perdida = productos_perdida.sort_values(by="Profit", ascending=True).head(10) - Se ordena de mas negativo a menos negativo y se toman los 10 primeros.')
doc.add_paragraph()
doc.add_heading('Generacion de la grafica (lineas 208-218)', 3)
doc.add_paragraph('sns.barplot(x="Profit", y="Product Name", ..., palette="rocket") - Barras horizontales donde Profit es el valor en X y Product Name en Y. La paleta rocket (morado intenso) se usa para resaltar las perdidas.')
doc.add_paragraph('El titulo es "Top 10 Productos con Mayores Perdidas". Se guarda como productos_perdida.png.')
doc.add_paragraph()

# ===== FLUJO =====
doc.add_heading('Flujo completo de ejecucion', 1)
doc.add_paragraph('1. Se llama a ejecutar_analisis(df) que prepara los datos y los guarda en el diccionario resultados.')
doc.add_paragraph('2. Se llama a generar_visualizaciones(resultados, df) que lee esos datos y produce las 5 imagenes PNG.')
doc.add_paragraph('3. Las imagenes se insertan despues en el reporte Word mediante doc.add_picture() dentro de generar_reporte_word().')
doc.add_paragraph()

# Save
doc.save('Explicacion_Graficas.docx')
print("Documento generado exitosamente")
